`readInput()`, but with choices!
earsketch/earsketch-webclient pull request #569
Opened 2023-07-06 21:52 UTC by manodrum

This new API function `readChoice()` provides script writers the ability to request input from a fixed set of choices.

For example:
```py
from earsketch import *

opts = [str(x) for x in range(0, 1000)]
res = multiChoiceInput("What's your favorite number?", opts)
print(res)

opts = [
    "belgian pop", "south carolina hip hop", "alternative country", 
    "gothic metal", "dubstep", "modern hard rock", 
    "japanese soundtrack", "nu disco", "indonesian folk", 
    "lo-fi cover", "houston rap"
]
res = multiChoiceInput("What's your favorite genre?", opts)
print(res)
```

Resolves https://github.com/GTCMT/earsketch/issues/3075

2023-07-10 17:59 UTC, heerman commented
Resolves GTCMT/earsketch#3075

See issue above for implementation discussion.

2023-08-09 19:02 UTC, heerman commented
Ash: begin implementing the consensus items from our discussion. Thanks.
https://github.com/GTCMT/earsketch/issues/3075#issuecomment-1671980472

2023-08-10 20:39 UTC, heerman commented
The most recent updates include buttons (sound browser style), "OKAY" button, and scrolling.

![readChoice fav number](https://github.com/GTCMT/earsketch-webclient/assets/43624284/5d047070-d48e-4c91-b918-ba52bef91b86)

2025-05-16 14:09 UTC, heerman requested changes
The testing went well. I tried different browser widths, different data types, early escape, etc...

I left a few minor code comments.

The modal styling and function is working well for me.

2025-05-16 14:09 UTC, heerman commented on .gitignore
> +/.zed
Do we need to ignore `.zed`? I'm ok with it, but also wondering why we need it if there's no other editor files (vscode or intellij)

2025-05-16 14:09 UTC, heerman commented on src/Utils.tsx
> +export const PromptChoice = ({ message, choices, isMultiChoice, close }: { message: string, choices: string[], isMultiChoice: boolean, close: (input: number | number[]) => void }) => {
I think the arg `isMultiChoice` is confusing. Can we rename to something like multi-select or allow-multiple?

2025-05-16 14:09 UTC, heerman commented on src/Utils.tsx
> +    const [currentChoice, setInput] = useState(-1)
Note: currently discussing default return, on escape, to be `0`.

2025-05-16 14:09 UTC, heerman commented on src/Utils.tsx
> +                                label={choice + "" /* coerce to string, for booleans */}
Objects will become `[Object object]`. This is probably fine though, since it's not really supported.

If we want to be cool and support objects, we could use `JSON.stringify(choice)` instead of `choice + ""`

2025-05-16 14:09 UTC, heerman commented on src/api/passthrough.ts
> +export function readChoice(result: DAWData, msg: string, choices: string[]) {
If we change the function name, please remember to update the names in the code too, for our future sanity.

2025-05-16 14:09 UTC, heerman commented on src/browser/Sounds.tsx
> +    return <OptionButton
Nice refactor sound browser button to `OptionButton` 👍 .

The name is good enough... but for me the word "option" doesn't add much. Maybe `CheckboxButton` or `ChipButton`? I don't feel too strongly about it though.

2025-05-16 14:09 UTC, heerman commented on src/locales/en/common.json
> +      "object": "Object",
Is this being used? I looked in `api.ts` and couldn't find it.

2025-05-16 15:41 UTC, manodrum commented on .gitignore
> +/.zed
we currently ignore vscode and IntelliJ in our `.gitignore` file. I did a lot of this recent work in Zed, so I included this. I can move it to a separate PR if you want to keep this clean.

2025-05-16 15:45 UTC, manodrum commented on .gitignore
> +/.zed
I'm moving them all to the top to make it more clear

2025-05-16 15:56 UTC, manodrum commented on src/Utils.tsx
> +    const [currentChoice, setInput] = useState(-1)
this one needs to start out of bounds so that none of the buttons are selected / highlighted when the prompt opens. Now, if we want to make default behavior clear in the UI by starting with the first choice selected, we could do this. I don't feel too strongly, except that starting with the first one selected will likely lead more users to just always select the first choice.

2025-05-16 15:59 UTC, manodrum commented on src/api/passthrough.ts
> +export function readChoice(result: DAWData, msg: string, choices: string[]) {
Done

2025-05-16 16:02 UTC, manodrum commented on src/browser/Sounds.tsx
> +    return <OptionButton
renamed to CheckboxButton

2025-05-16 16:05 UTC, manodrum commented on src/locales/en/common.json
> +      "object": "Object",
no. removing. Not sure how that ended up there. I'm going to blame AI. :)

2025-05-16 16:11 UTC, manodrum commented on src/locales/en/common.json
> +      "object": "Object",
oh, git blame says you added it to this PR a year ago,  So I'm not going crazy 😄

2025-05-16 16:16 UTC, manodrum commented on src/Utils.tsx
> +                                label={choice + "" /* coerce to string, for booleans */}
not sure why anyone would want to display a json object to a user, but sure, why not.

2025-05-16 18:22 UTC, heerman commented on .gitignore
> +/.zed
Sounds good

2025-05-16 18:25 UTC, heerman commented on src/Utils.tsx
> +                                label={choice + "" /* coerce to string, for booleans */}
Hmmm now all strings have quotes around them, I think it's a little strange. Maybe this wasn't a great idea.

Can we revert?

![stringified options](https://github.com/user-attachments/assets/63eb7b82-9bf5-441b-957a-54a740f16789)

2025-05-16 18:29 UTC, heerman requested changes
Looks great 🚴 

One thing: i think we should revert JSON.stringify to `+ ""`

2025-05-16 19:02 UTC, heerman approved these changes

2025-05-16 19:06 UTC, merged