EarSketch extensions framework
earsketch/earsketch-webclient pull request #664
Opened 2024-09-10 14:57 UTC by heerman

Resolves to GTCMT/earsketch#3324.

2026-02-26 13:10 UTC, heerman reviewed
Overall looks great Stephen. The extensions api looks fine to me.

Happy to see the minor improvements to `.env` and cypress commands.

I did leave a few minor comments related to my testing on the pr deployment.

2026-02-26 13:10 UTC, heerman commented on public/earsktch_extension_icon_128.png
This icon looks a bit odd, with the floating thin white line on the left, the non-centered note, and no anti-aliasing.

It'll be fine as is, but would be nice to address if it's a 2 second fix.

2026-02-26 13:10 UTC, heerman commented on src/ide/IDE.tsx
> +                        <div className={eastContent !== "curriculum" ? "hidden" : "h-full"}><Curriculum /></div>
Minor issue: At narrow widths, the curriculum header looks jumbled and there is a double scroll

<img width="302" height="514" alt="Image" src="https://github.com/user-attachments/assets/0450931f-ea3c-45a8-8312-ee46c9edb7c0" />

2026-02-26 13:10 UTC, heerman commented on src/extensions/ExtensionHost.tsx
> +                console.log("Received message from iframe:", event.data)
The example extension is not displaying anything for me, but I am getting this console message `Received message from iframe:`.

I'm also getting new relic warnings: `New Relic Warning: https://github.com/newrelic/newrelic-browser-agent/blob/main/docs/warning-codes.md#15 ReferenceError: can't access lexical declaration 's' before initialization`

Also fyi I had to load it with the full url `https://earsketch-test.ersktch.gatech.edu/pr-664/myExtension.html`

2026-02-26 13:10 UTC, heerman commented on src/browser/Curriculum.tsx
> +                        title={t("curriculum.title")}
The font looks funny on the "curriculum" button. I think it should match the grey buttons from the sound browser.

<img width="300" height="auto" alt="Image" src="https://github.com/user-attachments/assets/721d3faf-f7c8-40ac-aec8-587eb27eb5cc" />

<img width="300" height="auto" alt="Image" src="https://github.com/user-attachments/assets/3db45df1-0a56-41db-909d-34aa29445027" />

2026-02-26 15:47 UTC, heerman reviewed
Looks like the bubble tour overflow fix got reverted.

https://github.com/GTCMT/earsketch/issues/3462
https://github.com/earsketch/earsketch-webclient/pull/746

<img width="300" height="auto" alt="Image" src="https://github.com/user-attachments/assets/6259f1f8-19de-4b87-8e39-6ff1d1058b63" />

2026-02-27 21:25 UTC, ijc8 requested changes

2026-02-27 21:25 UTC, ijc8 commented on src/extensions/ExtensionHost.tsx
> +            return script.source_code
This throws a TypeError if there's no script open. (It's one thing if we ultimately want it to throw an error on the extension side, where the extension can catch it, but currently this is throwing on the host side.)

2026-02-27 21:25 UTC, ijc8 commented on src/extensions/ExtensionHost.tsx
> +            // TODO return a cleaned version of the daw state that can be serialized
Big TODO! What DAW data do we think extensions actually need?

2026-02-27 21:25 UTC, ijc8 commented on src/extensions/ExtensionHost.tsx
> +                return ""
I would also accept `null` (in which case we could simplify this to just they `else` branch, since `selectUserName` already returns `null` if the user isn't logged in).

2026-02-27 21:25 UTC, ijc8 commented on src/extensions/ExtensionHost.tsx
> +                        if (!permissions.includes("getScriptExecutionResult")) {
Can we reduce duplication on these permission checks? (And perhaps we could just index into `extensionFunctions` directly rather than having a big switch?)

2026-02-27 21:25 UTC, ijc8 commented on ARCHITECTURE.md
> +- `tests/` - Unit, component, and end-to-end tests
What's with the changes here and in `README.md`?

2026-02-27 21:25 UTC, ijc8 commented on public/example-extension/es-ext.json
> +  "version": "1.0",
Okay, so the manifest format is versioned, and the extension is versioned. Cool.
Should the extension API *also* be versioned, such that the extension can declare what version of the API it was written for? In the same way that e.g. an Android app's manifest declares what version of the SDK it's targeting.
(The idea being that we would then have a path to making breaking changes someday rather than just being stuck with the first version of this that we came up with forever. 😄)

2026-02-27 21:25 UTC, ijc8 commented on public/es-ext.json
> +    "sidePanel",
Out of curiosity, are we envisioning the possibility of extensions *without* this permission? Right now this is necessary for the extension to run at all, since otherwise there's no iframe and thus no JS.

2026-02-27 21:25 UTC, ijc8 commented on public/example-extension/myExtension.html
> +<!doctype html>
Should all the example extension stuff go directly in `public/`? Maybe could we put it in its own subdirectory?

2026-02-27 21:25 UTC, ijc8 commented on public/example-extension/myExtension.html
> +    // Setup code we can provide in the form of a module or external script
Are we punting this to a future PR?

2026-02-27 21:25 UTC, ijc8 commented on public/myExtension.html
> +                resolver = resolve;
Technically this should probably be a little more sophisticated - if an extension calls one of these functions without having `await`ed the results of all previous calls, the resolver from a previous call may be overwritten, preventing the promise from ever resolving.

For example, try putting this at the end of `onload` below:
```js
const promise = earsketch.getEditorContents()
const user = await earsketch.getCurrentUser()
console.log("got user:", user)
const contents = await promise
console.log("got contents:", contents) // never prints
```

Or, more simply:
```js
const [user, contents] = await Promise.all([earsketch.getCurrentUser(), earsketch.getEditorContents()])
console.log(user, contents) // never prints
```

This can be fixed by storing multiple resolvers and figuring out which one goes with which response from the host. If the host always processes requests in order, this can just be a queue; otherwise we'll need to introduce request IDs. Alternatively, we could stick with the discipline of "only one active request allowed", and have the functions here chain the promises to prevent the second `postMessage` from firing until after we've received the response from the first one.

2026-06-06 14:17 UTC, manodrum commented on public/example-extension/myExtension.html
> +<!doctype html>
moved

2026-06-06 14:24 UTC, manodrum commented on public/example-extension/es-ext.json
> +  "version": "1.0",
added extension api version

2026-06-06 14:33 UTC, manodrum commented on src/extensions/ExtensionHost.tsx
> +            return script.source_code
now returning empty string if activeTab or script are null

2026-06-06 14:42 UTC, manodrum commented on src/extensions/ExtensionHost.tsx
> +                return ""
I also accept this :) changed to `null`

2026-06-06 14:57 UTC, manodrum commented on src/extensions/ExtensionHost.tsx
> +                        if (!permissions.includes("getScriptExecutionResult")) {
done

2026-06-06 15:37 UTC, manodrum commented on public/earsktch_extension_icon_128.png
fixed

2026-06-06 15:44 UTC, manodrum commented on src/ide/IDE.tsx
> +                        <div className={eastContent !== "curriculum" ? "hidden" : "h-full"}><Curriculum /></div>
fixed

2026-06-06 15:48 UTC, manodrum commented on src/extensions/ExtensionHost.tsx
> +                console.log("Received message from iframe:", event.data)
this is resolved

2026-06-06 15:59 UTC, manodrum commented on src/browser/Curriculum.tsx
> +                        title={t("curriculum.title")}
fixed

2026-06-06 16:00 UTC, manodrum commented on public/example-extension/es-ext.json
> +    "sidePanel",
yes, there could be extensions that add API functions without a side panel display.

2026-06-06 16:00 UTC, manodrum commented on public/example-extension/myExtension.html
> +    // Setup code we can provide in the form of a module or external script
yes

2026-06-06 16:01 UTC, manodrum commented on public/example-extension/myExtension.html
> +                resolver = resolve;
for now, we are having extensions await all calls and manage this themselves. Yes, this should ideally be improved.

2026-06-06 16:11 UTC, manodrum approved these changes

2026-06-06 16:11 UTC, merged